#!/usr/bin/php
<?php
/*
Copyright 2009 Guillaume Boudreau

This file is part of Greyhole.

Greyhole is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Greyhole is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Greyhole.  If not, see <http://www.gnu.org/licenses/>.
*/

include('includes/common.php');
parse_config();

$total_space = 0;
$total_free_space = 0;
foreach ($storage_pool_directories as $target_drive) {
	$response = explode(' ', exec("df -k ".escapeshellarg($target_drive)." | tail -1 | awk '{print \$(NF-4),\$(NF-2)}'"));
	$total_space += $response[0];
	$total_free_space += $response[1];
}

echo "$total_space $total_free_space 1024\n";
?>
