#!/bin/sh
# Copyright 2010 Guillaume Boudreau
# 
# This file is part of Greyhole.
# 
# Greyhole is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Greyhole is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Greyhole.  If not, see <http://www.gnu.org/licenses/>.

if [ $# -gt 2 -o $# -lt 1 ]; then
	echo "Usage: $0 directory [files_suffix]"
	exit
fi

if [ $UID != 0 ]; then
	echo "You need to be root to execute this command."
	echo "You can become root using the following command: su -"
	exit
fi

DIR=$1

SUFFIX=""
if [ $# -gt 1 ]; then
	SUFFIX="-$2"
fi

for POOL_DIR in `grep storage_pool_directory ${DIR}/greyhole.conf${SUFFIX} | grep -v "[ \t]*#" | awk '{print $3}' | awk -F',' '{print $1}'`; do
	if [ ! -x $POOL_DIR ]; then
		echo "Error: Missing pool directory: $POOL_DIR"
		exit
	fi
	if [ ! -f $POOL_DIR/.greyhole_uses_this ]; then
		touch $POOL_DIR/.greyhole_uses_this
	fi
done

cp /etc/greyhole.conf /etc/greyhole.conf.bak
cp ${DIR}/greyhole.conf${SUFFIX} /etc/greyhole.conf
service greyhole restart

cp /etc/samba/smb.conf /etc/samba/smb.conf.bak
cp ${DIR}/smb.conf${SUFFIX} /etc/samba/smb.conf
service smb reload

if [ -f /var/hda/platform/html/config/database.yml ]; then
	# Amahi 'shares' database update
	DATABASE=`grep -A 10 "production:" /var/hda/platform/html/config/database.yml | grep "database:" | awk '{print $2}'`
	USERNAME=`grep -A 10 "production:" /var/hda/platform/html/config/database.yml | grep "username:" | awk '{print $2}'`
	PASSWORD=`grep -A 10 "production:" /var/hda/platform/html/config/database.yml | grep "password:" | awk '{print $2}'`
	for GREYHOLE_SHARE in `grep "^\[\|vfs objects.*greyhole" ${DIR}/smb.conf${SUFFIX} | grep -B 1 "vfs objects.*greyhole" | grep "^\[" | awk -F'[' '{print $2}' | awk -F']' '{print $1}'`; do
		mysql -u $USERNAME -p$PASSWORD -e "UPDATE shares SET extras = CONCAT(extras, '\ndfree command = /usr/bin/greyhole-dfree\nvfs objects = greyhole') WHERE comment = '$GREYHOLE_SHARE' AND extras NOT LIKE '%greyhole-dfree%'" $DATABASE
	done
fi
