#!/bin/bash
CACHE_DIR="/var/cache/greyhole-dfree"
CACHE_TIME=15 # in seconds

if [[ "$1" == /* ]]; then
	DIR="$1" # absolute path given, ignore working directory
else
	DIR="$(pwd)/$1" # relative path given, use working directory
fi

TMP_FILE="$CACHE_DIR/${DIR//"/"/_}"
RESULT="0 0 1024" # fail-safe default result

if [ ! -e "$CACHE_DIR" ]; then
	mkdir -p "$CACHE_DIR"
fi

if [ ! -e "$TMP_FILE" ]; then
	RESULT=$(/usr/bin/greyhole-dfree $1)
	echo "$RESULT" > "$TMP_FILE"
else
	MODIFIED=$(stat -c %Y "$TMP_FILE")
	CURRENT=$(date +%s)
	if [ $((CURRENT - MODIFIED)) -lt $CACHE_TIME ]; then
		RESULT=$(cat "$TMP_FILE")
	else
		# update cache by running greyhole-dfree
		RESULT=$(/usr/bin/greyhole-dfree $1)
		echo "$RESULT" > "$TMP_FILE"
	fi
fi

echo "$RESULT"
