#!/bin/bash
set -e

mkdir -p /var/spool/greyhole
chmod 777 /var/spool/greyhole

LIBDIR=/usr/lib
if [ "`uname -m`" = "x86_64" ]; then
	LIBDIR=/usr/lib64
fi
if [ -f ${LIBDIR}/samba/vfs/greyhole.so ]; then
	rm ${LIBDIR}/samba/vfs/greyhole.so
fi

SMB_VERSION="`smbd --version | awk '{print $2}' | awk -F'-' '{print $1}' | awk -F'.' '{print $1,$2}'`"
if [ "$SMB_VERSION" = "3 4" ]; then
	ln -s ${LIBDIR}/greyhole/greyhole-samba34.so ${LIBDIR}/samba/vfs/greyhole.so
elif [ "$SMB_VERSION" = "3 5" ]; then
	ln -s ${LIBDIR}/greyhole/greyhole-samba35.so ${LIBDIR}/samba/vfs/greyhole.so
elif [ "$SMB_VERSION" = "3 6" ]; then
	ln -s ${LIBDIR}/greyhole/greyhole-samba36.so ${LIBDIR}/samba/vfs/greyhole.so
elif [ "$SMB_VERSION" = "4 0" ]; then
	ln -s ${LIBDIR}/greyhole/greyhole-samba40.so ${LIBDIR}/samba/vfs/greyhole.so
else
	echo "Warning: Greyhole doesn't include a VFS module for your version of Samba ($SMB_VERSION)."
	echo "We will try to use the VFS for version 3.6, but that might not work."
	ln -s ${LIBDIR}/greyhole/greyhole-samba36.so ${LIBDIR}/samba/vfs/greyhole.so
fi

# For Ubuntu 11.10, where even x86_64 install use /usr/lib
if [ "`uname -m`" = "x86_64" -a -x /usr/lib/samba/vfs/ ]; then
	if [ -f /usr/lib/samba/vfs/greyhole.so ]; then
		rm /usr/lib/samba/vfs/greyhole.so
	fi
	if [ "$SMB_VERSION" = "3 4" ]; then
		ln -s ${LIBDIR}/greyhole/greyhole-samba34.so /usr/lib/samba/vfs/greyhole.so
	elif [ "$SMB_VERSION" = "3 5" ]; then
		ln -s ${LIBDIR}/greyhole/greyhole-samba35.so /usr/lib/samba/vfs/greyhole.so
	elif [ "$SMB_VERSION" = "3 6" ]; then
		ln -s ${LIBDIR}/greyhole/greyhole-samba36.so /usr/lib/samba/vfs/greyhole.so
	elif [ "$SMB_VERSION" = "4 0" ]; then
		ln -s ${LIBDIR}/greyhole/greyhole-samba40.so /usr/lib/samba/vfs/greyhole.so
	else
		ln -s ${LIBDIR}/greyhole/greyhole-samba36.so ${LIBDIR}/samba/vfs/greyhole.so
	fi
fi

if [ -f /proc/fs/cifs/OplockEnabled ]; then
	# cifs client workaround
	# Ref: http://blog.dhampir.no/content/cifs-vfs-no-response-for-cmd-n-mid
	modprobe cifs
	echo 0 > /proc/fs/cifs/OplockEnabled
fi
if [ -f /sys/module/cifs/parameters/enable_oplocks ]; then
	# cifs client workaround
	# Ref: http://blog.dhampir.no/content/cifs-vfs-no-response-for-cmd-n-mid
	modprobe cifs enable_oplocks=0
	echo 0 > /sys/module/cifs/parameters/enable_oplocks
fi

running=0
if [ -f /sbin/start ]; then
	# Using Upstart instead of SYSV init.d
	if [ -f /etc/init.d/greyhole ]; then
		rm /etc/init.d/greyhole
	fi
	if [ -f /etc/init/greyhole.conf ]; then
		if [ "`status greyhole | grep running | wc -l`" = "1" ]; then
			restart greyhole
			running=1
		fi
	fi
else
	# (SYSV) Service install & start
	if [ -f /etc/init/greyhole.conf ]; then
		rm /etc/init/greyhole.conf
	fi
	if [ -f /etc/init.d/mysql ]; then
	    sed -i 's/mysqld/mysql/' /etc/init.d/greyhole
    fi
    if [ -f /etc/init.d/samba ]; then
        sed -i 's/smb/samba/' /etc/init.d/greyhole
    fi
	if [ -f /sbin/chkconfig ]; then
		/sbin/chkconfig --add greyhole
		/sbin/chkconfig greyhole on
	else
		/usr/sbin/update-rc.d greyhole defaults
	fi
	if [ -f /etc/init.d/greyhole ]; then
		if [ "`service greyhole status | grep 'is running' | wc -l`" = "1" ]; then
			service greyhole restart
			running=1
		fi
	fi
fi

if [ $running -eq 0 ]; then
	echo "==========================================================================="
	echo "See /usr/share/greyhole/USAGE to learn how to configure and start Greyhole."
	echo "==========================================================================="
fi
